import Head from 'next/head';
import { BsFillMoonStarsFill } from "react-icons/bs";
import { FaBloggerB } from "react-icons/fa"
import { AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube } from 'react-icons/ai'
import Image from "next/image";
import deved from '../public/dev-ed-wave.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from "../public/web1.png"
import web2 from "../public/web2.png"
import web3 from "../public/web3.png"
import web4 from "../public/web4.png"
import web5 from "../public/web5.png"
import web6 from "../public/web6.png"
import { useState } from 'react';

export default function Home() {

  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Khairul Hafizuddeen Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className='py-10 mb-12 flex justify-between dark:text-white'>
            <h1 className='text-xl font-burtons'>HAFIZUDDEEN</h1>
            <ul className="flex items-center space-x-7">
              <li>
                <BsFillMoonStarsFill className='cursor-pointer text-2xl'
                  onClick={() => setDarkMode(!darkMode)} />
              </li>
              <li>
                <FaBloggerB className='cursor-pointer text-2xl' />
              </li>
              <li>
                <a className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md" href="#">
                  Resume</a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">Khairul Hafizuddeen</h2>
            <h3 className='text-2xl py-2 dark:text-white md:text-3xl'>Backend Developer and Devops</h3>
            <p className='text md py-5 leading-8 text-gray-800  dark:text-gray-200 md:text-xl max-w-lg mx-auto'>
              Programming and system design for fun! Hit me up if you have any interesting opportunity or for a cup of coffee ☕. It is always on me for the first time.
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400'>
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
            <Image src={deved} layout="fill" objectFit='cover' alt={''} />
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-10 dark:text-white'>Company and projects that I worked before</h3>
            <p className='text-md py-3 leading-8 text-gray-800 dark:text-gray-200'>
              Since the start of my career, I have worked in consultancy and stratups to create Saas softwares, products and services across the stacks.
              Mainly using <span className="text-teal-500">NodeJs, Angular, React, Azure and AWS</span>.
            </p>
            <p className='text-md py-3 leading-8 text-gray-800 dark:text-gray-200'>
              I am specialize in architecturing and setting up technologies in <span className="text-teal-500"> Kubernates, CI/CD pipelines and monitoring tools </span>.
              Also heavily involved in Backend technologies like <span className="text-teal-500">Caching, CRUD, Api Manager, logging</span>.
            </p>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1'>
              <Image className='inline-block' src={design} width={100} height={100} alt={''} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className='py-2'>
                Creating elegant designs suited for your needs following core design theory
              </p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1'>
              <Image className='inline-block' src={consulting} width={100} height={100} alt={''} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className='py-2'>
                Creating elegant designs suited for your needs following core design theory
              </p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl dark:bg-white my-10 flex-1'>
              <Image className='inline-block' src={code} width={100} height={100} alt={''} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className='py-2'>
                Creating elegant designs suited for your needs following core design theory
              </p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
          </div>
        </section>
        <section className='py-10'>
          <div>
            <h3 className='text-3xl py-1 dark:text-white'>Portfolio</h3>
            <p className='text-md py-3 leading-8 text-gray-800 dark:text-white'>
              Since the start of my career, I have worked in consultancy and stratups to create Saas softwares, products and services across the stacks.
              Mainly using <span className="text-teal-500">NodeJs, Angular, React, Azure and AWS</span>.
            </p>
            <p className='text-md py-3 leading-8 text-gray-800 dark:text-white'>
              I am specialize in architecturing and setting up technologies in <span className="text-teal-500"> Kubernates, CI/CD pipelines and monitoring tools </span>.
              Also heavily involved in Backend technologies like <span className="text-teal-500">Caching, CRUD, Api Manager, logging</span>.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover w-full h-full"
                layout="responsive"
                src={web1}
                alt={''}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover w-full h-full"
                layout="responsive"
                src={web2}
                alt={''}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover w-full h-full"
                layout="responsive"
                src={web3}
                alt={''}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover w-full h-full"
                layout="responsive"
                src={web4}
                alt={''}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover w-full h-full"
                layout="responsive"
                src={web5}
                alt={''}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover w-full h-full"
                layout="responsive"
                src={web6}
                alt={''}
              />
            </div>
          </div>
        </section>
      </main>
    </div >
  )
}
